import {JetBrains_Mono} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import { GoogleAnalytics } from "nextjs-google-analytics";
import Script from "next/script";
const jetbrainsMono = JetBrains_Mono({
    subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
    variable: '--font-jetbrainsMono'
})
export const metadata = {
    title: "My Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body
            className={`${jetbrainsMono.variable} ${jetbrainsMono.variable} antialiased`}
        >
        <Script
            strategy="afterInteractive"
            src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`}
        />
        <Script
            id="google-analytics"
            strategy="afterInteractive"
        >
            {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', '${process.env.NEXT_PUBLIC_GA_ID}');
            `}
        </Script>
        <Header/>
        <StairTransition/>
        <PageTransition>{children}</PageTransition>
        </body>
        </html>
    );
}
